# Codecov configuration for pipeworks_mud_server
# https://docs.codecov.com/docs/codecov-yaml

coverage:
  status:
    project:
      default:
        target: 80%  # Must maintain 80% project coverage
        threshold: 1%  # Allow 1% decrease before failing
    patch:
      default:
        target: 80%  # New code should have 80% coverage
        threshold: 1%

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
