"""
Pydantic models for API requests and responses.

This module defines all the data models used for API communication between
the FastAPI backend and clients (admin WebUI, API consumers). Pydantic models provide:
- Automatic request/response validation
- Type checking and conversion
- Clear API documentation via FastAPI's automatic OpenAPI schema generation
- Serialization/deserialization to/from JSON

Models are organized into two categories:
1. Request models: Data sent FROM the client TO the server
2. Response models: Data sent FROM the server TO the client
"""

from mud_server.api import models_admin as admin_models
from mud_server.api import models_auth_game as auth_game_models
from mud_server.api import models_lab as lab_models

CharacterAxisDelta = admin_models.CharacterAxisDelta
CharacterAxisEvent = admin_models.CharacterAxisEvent
CharacterAxisScore = admin_models.CharacterAxisScore
ChatPruneRequest = admin_models.ChatPruneRequest
ChatPruneResponse = admin_models.ChatPruneResponse
ClearOllamaContextRequest = admin_models.ClearOllamaContextRequest
ClearOllamaContextResponse = admin_models.ClearOllamaContextResponse
CreateCharacterRequest = admin_models.CreateCharacterRequest
CreateCharacterResponse = admin_models.CreateCharacterResponse
CreateUserRequest = admin_models.CreateUserRequest
CreateUserResponse = admin_models.CreateUserResponse
DatabaseCharacterAxisEventsResponse = admin_models.DatabaseCharacterAxisEventsResponse
DatabaseCharacterAxisStateResponse = admin_models.DatabaseCharacterAxisStateResponse
DatabaseChatResponse = admin_models.DatabaseChatResponse
DatabaseConnectionsResponse = admin_models.DatabaseConnectionsResponse
DatabasePlayerLocationsResponse = admin_models.DatabasePlayerLocationsResponse
DatabasePlayersResponse = admin_models.DatabasePlayersResponse
DatabaseSchemaForeignKey = admin_models.DatabaseSchemaForeignKey
DatabaseSchemaResponse = admin_models.DatabaseSchemaResponse
DatabaseSchemaTable = admin_models.DatabaseSchemaTable
DatabaseSessionsResponse = admin_models.DatabaseSessionsResponse
DatabaseTableInfo = admin_models.DatabaseTableInfo
DatabaseTableRowsResponse = admin_models.DatabaseTableRowsResponse
DatabaseTablesResponse = admin_models.DatabaseTablesResponse
DatabaseWorldStatusResponse = admin_models.DatabaseWorldStatusResponse
DatabaseWorldStatusRow = admin_models.DatabaseWorldStatusRow
KickCharacterRequest = admin_models.KickCharacterRequest
KickCharacterResponse = admin_models.KickCharacterResponse
KickSessionRequest = admin_models.KickSessionRequest
KickSessionResponse = admin_models.KickSessionResponse
ManageCharacterRequest = admin_models.ManageCharacterRequest
ManageCharacterResponse = admin_models.ManageCharacterResponse
OllamaCommandRequest = admin_models.OllamaCommandRequest
OllamaCommandResponse = admin_models.OllamaCommandResponse
ServerStopRequest = admin_models.ServerStopRequest
ServerStopResponse = admin_models.ServerStopResponse
UserListResponse = admin_models.UserListResponse
UserManagementRequest = admin_models.UserManagementRequest
UserManagementResponse = admin_models.UserManagementResponse
WorldActiveCharacterSession = admin_models.WorldActiveCharacterSession

ChangePasswordRequest = auth_game_models.ChangePasswordRequest
CharactersResponse = auth_game_models.CharactersResponse
CommandRequest = auth_game_models.CommandRequest
CommandResponse = auth_game_models.CommandResponse
LoginDirectRequest = auth_game_models.LoginDirectRequest
LoginDirectResponse = auth_game_models.LoginDirectResponse
LoginRequest = auth_game_models.LoginRequest
LoginResponse = auth_game_models.LoginResponse
LogoutRequest = auth_game_models.LogoutRequest
PlayerCreateCharacterRequest = auth_game_models.PlayerCreateCharacterRequest
RegisterGuestRequest = auth_game_models.RegisterGuestRequest
RegisterGuestResponse = auth_game_models.RegisterGuestResponse
RegisterRequest = auth_game_models.RegisterRequest
RegisterResponse = auth_game_models.RegisterResponse
SelectCharacterRequest = auth_game_models.SelectCharacterRequest
SelectCharacterResponse = auth_game_models.SelectCharacterResponse
StatusResponse = auth_game_models.StatusResponse

LabAxisValue = lab_models.LabAxisValue
LabImageCompileRequest = lab_models.LabImageCompileRequest
LabImageCompileResponse = lab_models.LabImageCompileResponse
LabImagePolicyBundleResponse = lab_models.LabImagePolicyBundleResponse
LabPolicyAxisDefinition = lab_models.LabPolicyAxisDefinition
LabPolicyBundleDraftCreateRequest = lab_models.LabPolicyBundleDraftCreateRequest
LabPolicyBundleDraftCreateResponse = lab_models.LabPolicyBundleDraftCreateResponse
LabPolicyBundleDraftDocument = lab_models.LabPolicyBundleDraftDocument
LabPolicyBundleDraftListResponse = lab_models.LabPolicyBundleDraftListResponse
LabPolicyBundleDraftPayload = lab_models.LabPolicyBundleDraftPayload
LabPolicyBundleDraftPromoteRequest = lab_models.LabPolicyBundleDraftPromoteRequest
LabPolicyBundleDraftPromoteResponse = lab_models.LabPolicyBundleDraftPromoteResponse
LabPolicyBundleDraftSummary = lab_models.LabPolicyBundleDraftSummary
LabPolicyBundleResponse = lab_models.LabPolicyBundleResponse
LabPolicyChatAxisRule = lab_models.LabPolicyChatAxisRule
LabPolicyChatRules = lab_models.LabPolicyChatRules
LabPolicyThresholdBand = lab_models.LabPolicyThresholdBand
LabPromptDraftCreateRequest = lab_models.LabPromptDraftCreateRequest
LabPromptDraftCreateResponse = lab_models.LabPromptDraftCreateResponse
LabPromptDraftDocument = lab_models.LabPromptDraftDocument
LabPromptDraftListResponse = lab_models.LabPromptDraftListResponse
LabPromptDraftPromoteRequest = lab_models.LabPromptDraftPromoteRequest
LabPromptDraftPromoteResponse = lab_models.LabPromptDraftPromoteResponse
LabPromptDraftSummary = lab_models.LabPromptDraftSummary
LabPromptFile = lab_models.LabPromptFile
LabTranslateRequest = lab_models.LabTranslateRequest
LabTranslateResponse = lab_models.LabTranslateResponse
LabWorldConfig = lab_models.LabWorldConfig
LabWorldPromptsResponse = lab_models.LabWorldPromptsResponse
LabWorldSummary = lab_models.LabWorldSummary
LabWorldsResponse = lab_models.LabWorldsResponse
